const skills = [
  "react.svg",
  "nextjs.svg",
  "js.svg",
  "html.svg",
  "css.svg",
  // "framer-motion.svg",
  "nodejs.svg",
  "express.svg",
  "python.svg",
  "bootstrap.svg",
  "git.svg",
  "github.svg",
  "mongodb.svg",
  "tailwind.svg",
  "linux.svg",
  "laravel.svg",
  "mysql.svg",
  "materialUI.svg",
  "firebase.svg",
  "vercel.svg",
  "react-native.svg",
  "docker.svg",
  "selenium.svg",
  "expo.svg",
  "figma_logo.png",
]; // Add or remove skills here, make sure to include the image respective to the skill inside the public/skills folder and use the correct file extension

export default skills;
